### ISSUE TITLE
C# RPC API Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by UvuvwevwevweOnyetenyevweUgwemubwemOssas** [LucidOcean/multichain#1]
I am trying to build an application with LucidOcean C# API, in the command line the mulitichain node is active.

I am not sure if I am doing it in the right way, I create a C# applicationi and try to connect to this multichain node by using methods from API.

Here is my code,

 MultiChainConnection connection = new MultiChainConnection()
            {
                Hostname = "127.0.0.1",
                Port = 4336,
                Username = "multichainrpc",
                Password = "password",
                ChainName = "chain1",
                BurnAddress = "1XXXXXXXZXXXXXXXZMXXXXXXXqXXXXXXbYgmzH",
                RootNodeAddress = "1TXfbuQzKGpDbTsAEAxdi7ZK5aUYTEVicUKWYT"
            };
            _Client = new MultiChainClient(connection);

...

...

     public JsonRpcResponse<List<string>> GetAddressesAsync()
        {
            JsonRpcResponse<List<string>> response = null;
            Task.Run(async () =>
            {
                response = await _Client.Wallet.GetAddressesAsync();
            }).GetAwaiter().GetResult();

            ResponseLogger<List<string>>.Log(response);

            return response;
        }

 

...

...

 

First question is, am I doing it in a right way?

2nd, How do I know if RPC is connected to the node?

3rd,  how to solve "Unexpected character encountered while parsing value: <. Path '', line 0, position 0."

 I am using Visual Studio 2015, Windows 10, and compiled LucidOcean-multichain into a .dll file, then I added .dll as a reference. 

Thanks a lot if anybody could help me a little.

**Comment by LucidOcean** [comment]
the syntax of the snippet appears correct. 

You will get an 'actively refused' if the node cannot be seen (firewall port closed or not running). 
For example,  "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"

A connection error will be received on the first call you make. 

try a simple call first to see if it will connect.
client.Utility.GetBlockChainParams() 

There are unit tests in the project. Try the Utility Tests first to ensure your connection settings are correct.

You can also run multichain-cli commandline with your connection settings to see if it is connecting generally.

**Comment by UvuvwevwevweOnyetenyevweUgwemubwemOssas** [comment]
Thanks for your reply.   I just ran unit test GetChainBlockParams with my customized setting, I only got error message below. Does it mean that the connection is OK? and the problem is about JSON?

Message: Test method MultiChainTests.UtilityTests.GetBlockChainParams threw exception: 
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by LucidOcean** [comment]
I believe your username/password is incorrect or other connection setting. Ensure your rpcallowip is configured to allow your IP and your password etc is correct.

I got your error in a test when the password is incorrect. I changed the source to bubble the exception to you. You will probably get 401 Unauthorised when you get latest.
